###
### Known to work with docker-compose version 1.7.1
###

nginx:
  build: ./nginx/nginx-with-logs
  container_name: nginx
  restart: always
  volumes:
    - /etc/nginx/conf.d
    - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
    - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    - /opt/vps/ssl_certs:/etc/nginx/certs
    - /opt/vps/nginx_logs:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"

dgen:
  image: jwilder/docker-gen
  environment:
    ENABLE_IPV6: "true"
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

site:
  image: nginx
  restart: always
  environment:
    VIRTUAL_HOST: viranch.me,www.viranch.me
    CERT_NAME: viranch.me
  volumes:
    - /opt/vps/viranch.github.io:/usr/share/nginx/html:ro

jdorg:
  image: nginx
  restart: always
  environment:
    VIRTUAL_HOST: jivandaan.org,www.jivandaan.org
    CERT_NAME: jivandaan.org
  volumes:
    - ./nginx/sites/jdorg:/usr/share/nginx/html:ro

indigo:
  build: /opt/vps/innerdialogue
  restart: always
  environment:
    VIRTUAL_HOST: innerdialogue.in,www.innerdialogue.in
    RACK_ENV: production
    ADMIN_EMAIL: ""
    SMTP_HOST: ""
    SMTP_USER: ""
    SMTP_PASS: ""

tv:
  image: viranch/tv
  restart: always
  hostname: linode-vps
  environment:
    VIRTUAL_HOST: vps.viranch.me
    CERT_NAME: viranch.me
    PB_TOKEN: secret
    RSS_FEED: http://followshows.com/feed/CCGYc,http://followshows.com/feed/0P9vRbdD
    TV_OPTS: "-suffix 720p,-suffix 720p"
  volumes:
    - /opt/vps/tv:/data

icinga:
  image: jeyk/icinga
  restart: always
  environment:
    VIRTUAL_HOST: icinga.viranch.me
    CERT_NAME: viranch.me
  volumes:
    - ./icinga/icinga.cfg:/etc/icinga/icinga.cfg:ro
    - ./icinga/resource.cfg:/etc/icinga/resource.cfg:ro
    - ./icinga/conf.d:/etc/icinga/conf.d:ro
    - ./icinga/htpasswd.users:/etc/icinga/htpasswd.users:ro
    - ./icinga/postfix-main.cf:/etc/postfix/main.cf
    - ./icinga/plugins/check_imap_quota:/usr/lib/nagios/plugins/check_imap_quota:ro
    - ./icinga/plugins/check_ssl:/usr/lib/nagios/plugins/check_ssl:ro
    - ./icinga/scripts:/opt/scripts
#    - ~/data:/check_data:ro

irc:
  image: clue/quassel-core
  restart: always
  volumes:
    - /opt/vps/quassel:/var/lib/quassel
  ports:
    - 9999:4242
  user: root
  #command: openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout /var/lib/quassel/quasselCert.pem -out /var/lib/quassel/quasselCert.pem

pihole:
  image: diginc/pi-hole
  restart: always
  environment:
    VIRTUAL_HOST: pihole.viranch.me
    CERT_NAME: viranch.me
    ServerIP: 172.104.161.244
    ServerIPv6: "2400:8901::f03c:91ff:fea7:5cb8"
    WEBPASSWORD: ''
  ports:
    - "53:53/tcp"
    - "53:53/udp"
  volumes:
    - /opt/vps/pihole/etc:/etc/pihole
    - /opt/vps/pihole/dnsmasq:/etc/dnsmasq.d

openvpn:
  image: kylemanna/openvpn
  restart: always
  volumes:
    - /opt/vps/openvpn/conf:/etc/openvpn
  ports:
    - "1194:1194/udp"
  cap_add:
    - NET_ADMIN
  #command: ovpn_genconfig -u udp://vps.viranch.me -n 172.104.161.244
  #command: ovpn_initpki # run with -it
  #command: easyrsa build-client-full viranch-vpn nopass # run with -it
  #command: ovpn_getclient viranch-vpn # save to viranch-vpn.ovpn file

netdata:
  image: firehol/netdata
  restart: always
  hostname: vps.viranch.me
  environment:
    VIRTUAL_HOST: netdata.viranch.me
    CERT_NAME: viranch.me
  volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
