###
### Known to work with docker-compose version 1.7.1
###

nginx:
  build: ./nginx/nginx-with-logs
  container_name: nginx
  restart: always
  volumes:
    - /etc/nginx/conf.d
    - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
    - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    - /opt/vps/ssl_certs:/etc/nginx/certs
    - /opt/vps/nginx_logs:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"

dgen:
  image: jwilder/docker-gen
  environment:
    ENABLE_IPV6: "true"
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

tv:
  image: viranch/tv
  restart: always
  hostname: linode-vps
  environment:
    VIRTUAL_HOST: vps.viranch.me
    CERT_NAME: viranch.me
    PB_TOKEN: ''
    RSS_FEED: http://showrss.info/user/204798.rss
    AUTH_USER: ''
    AUTH_PASS: ''
  volumes:
    - /opt/vps/tv:/data

plex:
  image: plexinc/pms-docker
  restart: always
  environment:
    VIRTUAL_HOST: plex.viranch.me
    VIRTUAL_PORT: 32400
    CERT_NAME: viranch.me
    TZ: America/Los_Angeles
    PLEX_CLAIM: ''
    ADVERTISE_IP: https://plex.viranch.me/
  ports:
    - "32400:32400"
  hostname: ''
  volumes:
    - /opt/vps/plex:/config
    - /opt/vps/tv/downloads:/data

icinga:
  image: jeyk/icinga
  restart: always
  environment:
    VIRTUAL_HOST: icinga.viranch.me
    CERT_NAME: viranch.me
  volumes:
    - ./icinga/icinga.cfg:/etc/icinga/icinga.cfg:ro
    - ./icinga/resource.cfg:/etc/icinga/resource.cfg:ro
    - ./icinga/conf.d:/etc/icinga/conf.d:ro
    - ./icinga/htpasswd.users:/etc/icinga/htpasswd.users:ro
    - ./icinga/postfix-main.cf:/etc/postfix/main.cf
    - ./icinga/plugins/check_imap_quota:/usr/lib/nagios/plugins/check_imap_quota:ro
    - ./icinga/plugins/check_ssl:/usr/lib/nagios/plugins/check_ssl:ro
    - ./icinga/scripts:/opt/scripts
    #- ~/data:/check_data:ro
