###
### Known to work with docker-compose version 1.7.1
###

nginx:
  image: nginx:alpine
  container_name: nginx
  restart: always
  environment:
    VIRTUAL_HOST: vps.viranch.me
  volumes:
    - /etc/nginx/conf.d
    - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
    - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    - /opt/vps/ssl_certs:/etc/nginx/certs
    - /opt/vps/nginx_logs:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"

dgen:
  build: ./docker-gen
  #image: jwilder/docker-gen
  environment:
    ENABLE_IPV6: "true"
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

files:
  image: viranch/dropbox
  restart: always
  environment:
    VIRTUAL_HOST: files.viranch.me
    CERT_NAME: vps.viranch.me
    AUTH_USER: ''
    AUTH_PASS: ''
  volumes:
    - /opt/vps/box:/data

icinga:
  image: jeyk/icinga
  restart: always
  environment:
    VIRTUAL_HOST: icinga.viranch.me
    CERT_NAME: vps.viranch.me
  volumes:
    - ./icinga/icinga.cfg:/etc/icinga/icinga.cfg:ro
    - ./icinga/resource.cfg:/etc/icinga/resource.cfg:ro
    - ./icinga/conf.d:/etc/icinga/conf.d:ro
    - ./icinga/htpasswd.users:/etc/icinga/htpasswd.users:ro
    - ./icinga/postfix-main.cf:/etc/postfix/main.cf
    - ./icinga/plugins/check_imap_quota:/usr/lib/nagios/plugins/check_imap_quota:ro
    - ./icinga/plugins/check_ssl:/usr/lib/nagios/plugins/check_ssl:ro
    - ./icinga/scripts:/opt/scripts
    - /opt/vps:/check_data:ro

tv:
  image: viranch/tv
  restart: always
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: viranch.tv
    PB_TOKEN: ''
    AUTH_USER: ''
    AUTH_PASS: ''
  volumes:
    - /opt/vps/tv:/data

vpn:
  build: ./wireguard
  container_name: vpn
  volumes:
    - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  privileged: true
