nginx:
  image: nginx:alpine
  container_name: nginx
  restart: always
  volumes:
    - /etc/nginx/conf.d
    - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    - /home/data/nginx_logs:/var/log/nginx
  ports:
    - "80:80"

dgen:
  image: nginxproxy/docker-gen
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

tv:
  image: ghcr.io/viranch/tv
  restart: always
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: tv.*,jk.*:9117
    PB_TOKEN: ''
    HOSTNAME: nuc
  volumes:
    - /home/data/tv:/data
    - /mnt/hdd2/downloads:/data/downloads:rslave
    - /mnt:/mnt/hdds:rslave

box:
  image: viranch/dropbox
  restart: always
  environment:
    VIRTUAL_HOST: files.*
  volumes:
    - /mnt:/data/mnt:ro,rslave

plex:
  image: plexinc/pms-docker
  restart: always
  environment:
    VIRTUAL_HOST: plex.*
    VIRTUAL_PORT: 32400
    TZ: America/Los_Angeles
    ADVERTISE_IP: http://plex.vrn.ch/
    PLEX_CLAIM: ''
  # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
  ports:
    - "32400:32400"
    - "32410:32410/udp"
    - "32412-14:32412-14/udp"
  volumes:
    - /home/data/plex2/config:/config
    - /mnt:/media/hdds:ro,rslave

stubby:
  image: mvance/stubby
  restart: always
  net: "container:pihole"
  volumes:
    - ./stubby.yml:/opt/stubby/etc/stubby/stubby.yml

pihole:
  image: pihole/pihole
  restart: always
  container_name: pihole
  environment:
    VIRTUAL_HOST: pi.hole,pihole.*
    PIHOLE_DNS_: "127.0.0.1#8053"
    ServerIP: 10.1.1.7
    TZ: America/Los_Angeles
    WEBPASSWORD: fuckyouads
  ports:
    - "10.1.1.7:53:53/tcp"
    - "10.1.1.7:53:53/udp"
  volumes:
    - /home/data/pihole/etc-pihole:/etc/pihole
    - /home/data/pihole/etc-dnsmasq:/etc/dnsmasq.d
    - ./pihole/vrnch.conf:/etc/dnsmasq.d/99-vrnch.conf:ro

vpn:
  build: ./wireguard
  container_name: vpn
  volumes:
    - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  privileged: true

org:
  image: organizr/organizr
  restart: always
  environment:
    VIRTUAL_HOST: home.*,vrn.ch
    fpm: "true"
    branch: v2-master
  volumes:
    - /home/data/org:/config

prow:
  image: lscr.io/linuxserver/prowlarr:develop
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: prow.*
    VIRTUAL_PORT: 9696
    TZ: America/Los_Angeles
    PUID: 0
    PGID: 0
  volumes:
    - /home/data/prowlarr:/config

radarr:
  image: lscr.io/linuxserver/radarr
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: radarr.*
    VIRTUAL_PORT: 7878
    TZ: America/Los_Angeles
    PUID: 0
    PGID: 0
  volumes:
    - /home/data/radarr:/config
    - /mnt/hdd2/downloads:/data/downloads:rslave

sonarr:
  image: lscr.io/linuxserver/sonarr
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: sonarr.*
    VIRTUAL_PORT: 8989
    TZ: America/Los_Angeles
    PUID: 0
    PGID: 0
  volumes:
    - /home/data/sonarr:/config
    - /mnt/hdd2/downloads:/data/downloads:rslave

gateway:
  image: ghcr.io/linuxserver/wireguard
  restart: always
  environment:
    PUID: 1000
    PGID: 1000
    TZ: America/Los_Angeles
    SERVERURL: wg.viranch.me
    PEERS: 5
    ALLOWEDIPS: 10.1.0.0/16,10.13.13.1/32
  volumes:
    - /home/data/wg:/config
    - /lib/modules:/lib/modules
  ports:
    - 51820:51820/udp
  cap_add:
    - NET_ADMIN

mintable:
  build: ./mintable
  environment:
    VIRTUAL_HOST: mint.*
    VIRTUAL_PORT: 8000
  volumes:
    - ./mintable/mintable.jsonc:/root/mintable.jsonc
  command: mintable account-setup
