nginx:
  image: nginx:alpine
  container_name: nginx
  restart: always
  volumes:
    - /etc/nginx/conf.d
    - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    - /home/data/nginx_logs:/var/log/nginx
    - ./nginx/certs:/etc/nginx/certs
    - ./nginx/vhosts:/etc/nginx/vhost.d
  ports:
    - "80:80"
    - "443:443"

dgen:
  #image: jwilder/docker-gen
  build: ./docker-gen
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

tv:
  image: viranch/tv
  restart: always
  net: "container:vpn"
  environment:
    VIRTUAL_HOST: tv.*,jk.*:9117
    PB_TOKEN: ''
    RSS_FEED: http://showrss.info/user/204798.rss
    AUTH_USER: ''
    AUTH_PASS: ''
  volumes:
    - /home/data/tv:/data
    - /mnt:/mnt/hdds:rslave

box:
  image: viranch/dropbox
  restart: always
  environment:
    VIRTUAL_HOST: files.*
  volumes:
    - /mnt/hdd2/data:/data:rslave

plex:
  image: plexinc/pms-docker
  restart: always
  environment:
    VIRTUAL_HOST: plex.viranch.me
    VIRTUAL_PORT: 32400
    CERT_NAME: home.viranch.me
    TZ: America/Los_Angeles
    ADVERTISE_IP: https://plex.viranch.me/
    PLEX_CLAIM: ''
  # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
  ports:
    - "32400:32400"
    - "32410:32410/udp"
    - "32412-14:32412-14/udp"
  volumes:
    - /home/data/plex2/config:/config
    - /home/data/tv/downloads:/media/tor:ro
    - /home/neo/downloads/movies:/media/movies:ro
    - /home/neo/downloads/tv:/media/tv:ro
    - /home/neo/downloads/kids:/media/kids:ro
    - /mnt:/media/hdds:ro,rslave

stubby:
  image: mvance/stubby
  restart: always
  net: "container:pihole"
  volumes:
    - ./stubby.yml:/opt/stubby/etc/stubby/stubby.yml

pihole:
  image: pihole/pihole
  restart: always
  container_name: pihole
  environment:
    VIRTUAL_HOST: pi.hole
    DNS1: "127.0.0.1#8053"
    DNS2: "no"
    ServerIP: 192.168.0.102
    TZ: America/Los_Angeles
    WEBPASSWORD: fuckyouads
  ports:
    - "192.168.0.102:53:53/tcp"
    - "192.168.0.102:53:53/udp"
  volumes:
    - /home/data/pihole/etc-pihole:/etc/pihole
    - /home/data/pihole/etc-dnsmasq:/etc/dnsmasq.d

vpn:
  build: ./wireguard
  container_name: vpn
  volumes:
    - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  privileged: true

org:
  image: organizr/organizr
  restart: always
  environment:
    VIRTUAL_HOST: home.*
    fpm: "true"
    branch: v2-master
  volumes:
    - /home/data/org:/config

bobarr-api:
  build: https://github.com/viranch/bobarr.git#fork:packages/api
  environment:
    ENV: production
    TZ: America/Los_Angeles
    UMASK_SET: 0002
    PUID: 0
    PGID: 0
    POSTGRES_DB: bobarr
    POSTGRES_USER: bobarr
    POSTGRES_PASSWORD: bobarr
    REDIS_PASSWORD: bobarr
    JACKETT_AUTOMATIC_SEARCH_TIMEOUT: 120000
    JACKETT_MANUAL_SEARCH_TIMEOUT: 15000
    LIBRARY_MOVIES_FOLDER_NAME: movies
    LIBRARY_TV_SHOWS_FOLDER_NAME: tvshows
    DEBUG_REDIS: "false"
    VIRTUAL_HOST: bobarr-api
  links:
    - postgres:postgres
    - redis:redis
    - tv:jackett
    - tv:transmission
  volumes:
    - /home/data/tv/downloads:/usr/library/downloads/complete
    - /mnt/hdd2/Movies/English:/usr/library/movies:rslave
    - /mnt/hdd2/TV Shows:/usr/library/tvshows:rslave
  command: yarn start:prod

bobarr-web:
  build: https://github.com/viranch/bobarr.git#fork:packages/web
  environment:
    ENV: production
    TZ: America/Los_Angeles
    UMASK_SET: 0002
    PUID: 0
    PGID: 0
    VIRTUAL_HOST: bobarr.*
  links:
    - bobarr-api:api
  command: yarn start

postgres:
  image: postgres:12-alpine
  environment:
    POSTGRES_DB: bobarr
    POSTGRES_USER: bobarr
    POSTGRES_PASSWORD: bobarr
  volumes:
    - /home/data/bobarr/postgres:/var/lib/postgresql/data

redis:
  image: bitnami/redis:5.0.6
  environment:
    REDIS_PASSWORD: bobarr
  volumes:
    - /home/data/bobarr/redis:/bitnami/redis/data
