#!/bin/bash

remote=$1
test -z "$remote" && echo 'error: no remote given' && exit 1

msg="$(curl -Sso/dev/null https://$remote/ 2>&1)"
[[ $? -ne 0 ]] && echo "CRITICAL - $msg" && exit 2

expiry=`echo | openssl s_client -connect $remote:443 -servername $remote 2>/dev/null | openssl x509 -noout -text | grep -oP 'Not After :\K.*'`
expiry_date=`date -d "$expiry" +%s`
today=`date +%s`

until_expiry=$(( ($expiry_date - $today)/(60*60*24) ))

msg="Certificate '$remote' will expire on $(date -d "$expiry")"

[[ $until_expiry -le $2 ]] && echo "CRITICAL - $msg" && exit 2

echo "OK - $msg"
