#!/usr/bin/python

import argparse
import imaplib
import re
import sys

args = argparse.ArgumentParser()
args.add_argument('-H', '--host')
args.add_argument('-P', '--port', type=int, default=993)
args.add_argument('-u', '--username')
args.add_argument('-p', '--password')
args.add_argument('-w', '--warning', type=int)
args.add_argument('-c', '--critical', type=int)
args = args.parse_args()

numbers = re.compile('\d+')

if args.host is None:
    args.host = 'imap.'+args.username.split('@')[-1]

mail = imaplib.IMAP4_SSL(args.host, args.port)
mail.login(args.username, args.password)

quota = mail.getquotaroot("INBOX")[1][1][0]
r = numbers.findall(quota)
used, total = r[0], r[1]
usage = float(used)*100.0/float(total)

try:
    mail.logout()
except:
    pass

print '{0}% used'.format(round(usage, 2))

if usage >= args.critical:
    sys.exit(2)
if usage >= args.warning:
    sys.exit(1)
